# Generated by Django 4.0.1 on 2022-01-22 22:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_created_date_task_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
